trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -L -O https://github.com/loadimpact/k6/releases/download/v0.34.1/k6-v0.34.1-linux64.tar.gz
      tar -xzf k6-v0.34.1-linux64.tar.gz
      mv k6-v0.34.1-linux64/k6 /usr/local/bin/
      rm -rf k6-v0.34.1-linux64 k6-v0.34.1-linux64.tar.gz

- script: k6 run index.js
  displayName: 'Run k6 Tests'
