trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: npm install -g k6
  displayName: 'Install k6'

- script: k6 run index.js
  displayName: 'Run k6 Tests'